---
# the main.yml file will simply be used to include necessary other task files

- include_tasks: install.yml
  with_items: "{{ repos }}"
  loop_control:
    loop_var: repo
  when: repos is defined
